### ISSUE TITLE
Feature request for a Boot mode option on the builder

### ISSUE THREAD

**Issue by philof** [hashicorp/packer-plugin-amazon#112]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add a boot_mode argument to the Amazon builder to specify `uefi` or `legacy-bios`

#### Use Case(s)

Graviton instance types run on UEFI.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-boot.html#set-ami-boot-mode

#### Potential configuration

```
{   
    "builders":[
        {
            "type": "amazon-ebs",
            "access_key": "{{user `accesskey`}}",
            "secret_key": "{{user `secretkey`}}",
            "region": "ap-south-1",
            "source_ami": "ami-sa7608343426b",
            "instance_type": "t2.micro",
            "ssh_username": "ubuntu",
            "ami_name": "nginx",
            "boot_mode": "uefi",
            "tags": {
              "OS_Version": "Ubuntu",
              "Release": "Latest"
            }
        }   
    ]
}
```

**Comment by yvlasenko** [comment]
Gravitron instances use UEFI by default even if `BootMode` flag not set.

I guess the use case would be to launch x86_64 instances in UEFI mode instead since they would launch in Legacy mode by default.

**Comment by bashoKa** [comment]
Hi
Good request. Wanna throw some attention here, it would really help us, if the builder would support the boot-mode option.
thnx already
