### ISSUE TITLE
SSH handshake failure when building Fedora AMI

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#118]
_This issue was originally opened by @solemnwarning in https://github.com/hashicorp/packer/issues/11179 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

I'm trying to create a Fedora-based AMI on EC2 using Packer, but each time I try running the build, it errors out with an SSH authentication failure. I am able to log in to the base AMI if I boot it manually via the AWS console, can't find Packer's own SSH key when it fails (as described in https://www.packer.io/docs/debugging), to try it myself at that point.

#### Reproduction Steps

Run included pkr.hcl file, example output:

```
==> fedora-test.amazon-ebs.fedora-test: Waiting for SSH to become available...
==> fedora-test.amazon-ebs.fedora-test: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Full debug log is attached.

[err.log](https://github.com/hashicorp/packer/files/6911063/err.log)

### Packer version

Packer v1.7.4

### Simplified Packer Buildfile

```
packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

source "amazon-ebs" "fedora-test" {
  ami_name      = "fedora-test-{{ isotime `20060102-150405` }}"
  instance_type = "t2.micro"
  region        = "us-east-2"
  
  source_ami_filter {
    filters = {
      name                = "Fedora-Cloud-Base-34-*.x86_64-hvm-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    
    most_recent = true
    owners      = ["679593333241"]
  }
  
  ssh_username = "fedora"
}

build {
  name    = "fedora-test"
  sources = [
    "source.amazon-ebs.fedora-test"
  ]
}
```

### Operating system and Environment details

Debian 10 (buster), amd64, using `packer` package from `apt.releases.hashicorp.com`.

**Comment by solemnwarning** [comment]
This only happens with Fedora 33/34 images, with the following in the SSH log:

```
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Connection closed by authenticating user fedora 82.71.51.99 port 51430 [preauth]
error: kex_exchange_identification: Connection closed by remote host
```

So it looks the same as https://github.com/hashicorp/terraform/issues/29082, since this is a Go SSH library, is there any possible workaround besides preparing an AMI that accepts the SHA1 RSA keys? The Go maintainers don't seem to be prioritising it going by the thread on their bug...

**Comment by solemnwarning** [comment]
The workaround at https://github.com/hashicorp/packer/issues/10074#issuecomment-886137013 worked for me, closing this ticket since you've already got others tracking this issue

Keep up the good work!

**Comment by azr** [comment]
Closing this thanks !

**Comment by lorengordon** [comment]
Hi @azr, it's actually already covered in #144. (Saw that one after posting the comment on this one.)
