### ISSUE TITLE
packer-builder-amazon-ebs plugin: create request failed InvalidTagKey.Malformed: Tag specification must have at least one tag

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#141]
_This issue was originally opened by @victoronto in https://github.com/hashicorp/packer/issues/11311 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

packer build with working AWS profile: successfully find vpc, subnet and ami....

packer-builder-amazon-ebs plugin: create request failed InvalidTagKey.Malformed: Tag specification must have at least one tag

#### Reproduction Steps

packer build -var aws_profile=dxp <buildfile>

### Packer version

1.7.6

### Simplified Packer Buildfile

With or without tags, run_tags and/or run_volume_tags

### Operating system and Environment details

```
$ uname -a
Linux f70a59901cf6 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux
```

### Log Fragments and crash.log files

```
==> amazon-ebs: Launching a spot AWS instance...
==> amazon-ebs: Interpolating tags for spot instance...
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Loading User Data File...
    amazon-ebs: Creating Spot Fleet launch template...
    amazon-ebs: Created Spot Fleet launch template: lt-01af447d2778bacf2
2021/10/06 22:37:56 packer-builder-amazon-ebs plugin: create request failed InvalidTagKey.Malformed: Tag specification must have at least one tag
2021/10/06 22:37:56 packer-builder-amazon-ebs plugin:   status code: 400, request id: 0dc8dab1-72b5-47a5-a87d-3f5b5ca83cd7
==> amazon-ebs: InvalidTagKey.Malformed: Tag specification must have at least one tag
==> amazon-ebs:         status code: 400, request id: 0dc8dab1-72b5-47a5-a87d-3f5b5ca83cd7
==> amazon-ebs:         status code: 400, request id: 0dc8dab1-72b5-47a5-a87d-3f5b5ca83cd7
==> amazon-ebs:         status code: 400, request id: 0dc8dab1-72b5-47a5-a87d-3f5b5ca83cd7
==> amazon-ebs: InvalidTagKey.Malformed: Tag specification must have at least one tag
==> amazon-ebs:         status code: 400, request id: 0dc8dab1-72b5-47a5-a87d-3f5b5ca83cd7
==> amazon-ebs: Step "StepRunSpotInstance" failed
```

**Comment by nywilken** [comment]
Hi @victoronto thanks for reaching out. Do you have an example template that we can use to reproduce the issue?

**Comment by victoronto** [comment]
`
{
    "builders": [{
        "access_key": "{{user `aws_access_key`}}",
        "ami_name": "app_deploy_{{timestamp}}",
        "instance_type": "t3.large",
        "profile": "{{user `aws_profile`}}",
        "region": "eu-west-1",
        "run_tags": {
            "Name": "app_deploy",
            "CreatedBy": "Packer",
            "PackerVersion": "{{user `packer_version`}}",
            "Env": "prod",
            "Scope": "app"
        },
        "run_volume_tags": {
            "Name": "app_deploy",
            "CreatedBy": "Packer",
            "PackerVersion": "{{user `packer_version`}}",
            "Env": "prod",
            "Scope": "app"
        },
        "secret_key": "{{user `aws_secret_key`}}",
        "source_ami_filter": {
            "filters": {
                "name": "app_latest_*",
                "root-device-type": "ebs",
                "virtualization-type": "hvm"
            },
            "owners": ["1234567890"],
            "most_recent": true
        },
        "launch_block_device_mappings": [{
            "device_name": "/dev/xvda",
            "delete_on_termination": true,
            "volume_size": 30,
            "volume_type": "gp2"
        }],
        "ami_block_device_mappings": [{
            "device_name": "/dev/xvda",
            "delete_on_termination": true,
            "volume_type": "gp2",
            "volume_size": 30
        }],
        "vpc_id": "vpc-0060000000000",
        "subnet_id": "subnet-0000000000",
        "associate_public_ip_address": "true",
        "spot_price": "auto",
        "ssh_interface": "public_ip",
        "ssh_username": "ec2-user",
        "tags": {
            "Name": "app_deploy",
            "CreatedBy": "Packer",
            "PackerVersion": "{{user `packer_version`}}",
            "Env": "prod",
            "Scope": "app"
        },
        "temporary_iam_instance_profile_policy_document": {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "ec2:CreateLaunchTemplate",
                  "ec2:DeleteLaunchTemplate",
                  "ec2:CreateFleet",
                  "ec2:DescribeSpotPriceHistory",
                  "ec2:DescribeVpcs",
                  "ec2:AttachVolume",
                  "ec2:AuthorizeSecurityGroupIngress",
                  "ec2:CopyImage",
                  "ec2:CreateImage",
                  "ec2:CreateKeypair",
                  "ec2:CreateSecurityGroup",
                  "ec2:CreateSnapshot",
                  "ec2:CreateTags",
                  "ec2:CreateVolume",
                  "ec2:DeleteKeyPair",
                  "ec2:DeleteSecurityGroup",
                  "ec2:DeleteSnapshot",
                  "ec2:DeleteVolume",
                  "ec2:DeregisterImage",
                  "ec2:DescribeImageAttribute",
                  "ec2:DescribeImages",
                  "ec2:DescribeInstances",
                  "ec2:DescribeInstanceStatus",
                  "ec2:DescribeRegions",
                  "ec2:DescribeSecurityGroups",
                  "ec2:DescribeSnapshots",
                  "ec2:DescribeSubnets",
                  "ec2:DescribeTags",
                  "ec2:DescribeVolumes",
                  "ec2:DetachVolume",
                  "ec2:GetPasswordData",
                  "ec2:ModifyImageAttribute",
                  "ec2:ModifyInstanceAttribute",
                  "ec2:ModifySnapshotAttribute",
                  "ec2:RegisterImage",
                  "ec2:RunInstances",
                  "ec2:StopInstances",
                  "ec2:TerminateInstances",
                  "ssm:DescribeParameters",
                  "ssm:Get*"
                ],
                "Resource": "*"
              },
              {
                "Effect": "Allow",
                "Action": [
                   "s3:*"
                ],
                "Resource": [
                   "arn:aws:s3:::asdfsdfas"
                ]
              }
            ]
        },
        "type": "amazon-ebs"
    }],
    "post-processors": [],
    "provisioners": [],
    "variables": {
        "aws_profile": "dxtest1",
        "packer_version": "{{env `PACKER_VERSION`}}"
    }
}`

**Comment by nywilken** [comment]
Okay, quickly looking at the debug logs I can see that you are using an older version of the Amazon builder called `packer-builder-amazon-ebs`? 

```
==> amazon-ebs: Creating temporary keypair: packer_615f6196-a887-f7a0-615b-83a837e0f47d
==> amazon-ebs: Creating temporary security group for this instance: packer_615f6197-b8ee-0732-7af9-593757f18d2f
2021/10/07 21:07:35 packer-builder-amazon-ebs plugin: [DEBUG] Waiting for temporary security group: sg-00a4c8cd30ed6dd87
2021/10/07 21:07:35 packer-builder-amazon-ebs plugin: [DEBUG] Found security group sg-00a4c8cd30ed6dd87
```

Do you by chance have a binary called `packer-builder-amazon-ebs` installed somewhere in Packer's directory that it is being loaded? 

Maybe you have a packer config variable set so Packer is looking for plugins in a different location. 
At the beginning of the debug logs you should be able to see what plugins are being loaded and from where. If the test binary is being loaded you would see something like

```
2021/10/07 18:06:24 [TRACE] Starting external plugin ~/Development/go/bin/packer-plugin-amazon start builder ebs
2021/10/07 18:06:24 Starting plugin: ~/Development/go/bin/packer-plugin-amazon []string{"~/Development/go/bin/packer-plugin-amazon", "start", "builder", "ebs"}
....

2021/10/07 18:02:58 Waiting for RPC address for: ~/.packer.d/plugins/packer-plugin-amazon
2021/10/07 18:02:58 Received unix RPC address for ~/.packer.d/plugins/packer-plugin-amazon: addr is /var/folders/vz/rv7bk6v15211jxg8q801f7kw0000gq/T/packer-plugin1441566612
2021/10/07 18:02:58 packer-plugin-amazon plugin: 2021/10/07 18:02:58 Plugin address: unix /var/folders/vz/rv7bk6v15211jxg8q801f7kw0000gq/T/packer-plugin1441566612
2021/10/07 18:02:58 packer-plugin-amazon plugin: 2021/10/07 18:02:58 Waiting for connection...
2021/10/07 18:02:58 packer-plugin-amazon plugin: 2021/10/07 18:02:58 Serving a plugin connection...
2021/10/07 18:02:58 packer-plugin-amazon plugin: 2021/10/07 18:02:58 [TRACE] starting builder ebs
2021/10/07 18:02:58 Preparing build: amazon-ebs

```

**Comment by nywilken** [comment]
I should add that depending our your OS the location of the plugins directory might be different. See [here](https://www.packer.io/docs/plugins#installing-plugins) for details for each OS. I kind of assumed *nix Os given the `ls` command but you might be using `WSL` on Windows.
