### ISSUE TITLE
Packer leaving keypairs in the AWS environment

### ISSUE THREAD

**Issue by rosenfelda** [hashicorp/packer-plugin-amazon#169]
#### Overview of the Issue

Packer is failing to delete/clean up key pairs in AWS at the end of an AMI build.  This is leading to a buildup of unused keypairs in our environment, which must be manually deleted.  I have only used Packer to build Windows AMIs based on Amazon's base images, so it is possible (but not certain) that this issue is particular to Windows AMI builds.

The keypairs can be seen in the AWS management console under EC2 / Network & Security / Key Pairs

The keypairs have names like "packer_60ca1335-412c-8063-791b-1d7141a74e1a"

#### Reproduction Steps

Our build does the following:
1. Create an AWS instance using the Windows 2019 base image
2. Push and execute several PowerShell scripts to configure the instance
3. Force a restart of the instance
4. Generate the AMI

### Plugin and Packer version

packer 1.7.5
I don't know the version of the AWS plugin, and I can't seem to get Packer to tell me.

### Simplified Packer Buildfile

The buildfile is 220 lines long, and is not in GitHub.  I can provide it to you if you let me know where to send it.

### Operating system and Environment details

My development machine is an EC2 instance running Windows 2019.  I use VS Code, and run Packer in a git-bash shell inside of VS Code.  Our automated Packer builds run in GitLab and execute in the Hashicorp Packer container on an Ubuntu Docker host.  Either build leaves keypairs behind.

### Log Fragments and crash.log files

I am attaching a screenshot of the AWS management console showing the keypairs.
<img width="1161" alt="key-pairs-redacted" src="https://user-images.githubusercontent.com/96262697/146442388-753c7faf-52d6-41fc-8f00-583b646f7144.png">

**Comment by JenGoldstrich** [comment]
@rosenfelda  Thanks for uploading this issue, I tried to reproduce it with a basic build file but wasn’t able to. 

Can we get the log output from a Packer build that results in a key-pair being left behind, if you watch a Packer build with the AWS plugin you should see something like `Creating temporary keypair: packer_61c2299a-22ef-61ce-fd1e-39d3f79ace1e`, you can then verify that after the build that key hasn’t been deleted and show us the full output from that command.    

Can we also get your build file, putting the contents of it in a GitHub comment is fine if you’re comfy with that

**Comment by JenGoldstrich** [comment]
@rosenfelda Closing this given its been a few months, please feel free to re-open if you have any other questions or want to dig into this further
