### ISSUE TITLE
AMI Sharing to AWS Organizations: Unsupported Argument

### ISSUE THREAD

**Issue by jered-miller** [hashicorp/packer-plugin-amazon#171]
#### Overview of the Issue

Attempting to share my image out to AWS Orgs using `ami_org_arns` returns "An argument named "ami_org_arns" is not expected here.".  Support was added for this in #158 if I read correctly.

#### Reproduction Steps

Use the amazon-ebs source and specify `ami_org_arns`

### Plugin and Packer version

packer --version
1.7.8

`Found the following "github.com/hashicorp/amazon" installations: [{/home/jered/.config/packer/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.0.6_x5.0_linux_amd64 v1.0.6}]`

### Simplified Packer Buildfile

[Build File](https://gist.github.com/jered-miller/7614773de989a6cee47b280d2b761a25)

### Operating system and Environment details

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### Log Fragments and crash.log files

[Debug Log](https://gist.github.com/jered-miller/03212136d9d31fc120ad3085f62d3e77)

**Comment by richardsonky** [comment]
I'm seeing the same problem as well.

**Comment by jeffadams** [comment]
Also seeing this behavior. Any updates?

**Comment by gek0** [comment]
> Seems to work if you configure plugin as "amazon" instead of "amazon-ebs".
> 
> ```
> packer {
>   required_plugins {
>     amazon-ebs = {
>       version = ">= 1.0.6"
>       source = "github.com/hashicorp/amazon"
>     }
>   }
> }
> ```
> 
> becomes
> 
> ```
> packer {
>   required_plugins {
>     amazon = {
>       version = ">= 1.0.6"
>       source = "github.com/hashicorp/amazon"
>     }
>   }
> }
> ```

Still the same for me, I've updated it to `amazon`, re-run packer init -upgrade <my_hcl_file> and getting the same error

**Comment by jered-miller** [comment]
> Seems to work if you configure plugin as "amazon" instead of "amazon-ebs".
> 
> ```
> packer {
>   required_plugins {
>     amazon-ebs = {
>       version = ">= 1.0.6"
>       source = "github.com/hashicorp/amazon"
>     }
>   }
> }
> ```
> 
> becomes
> 
> ```
> packer {
>   required_plugins {
>     amazon = {
>       version = ">= 1.0.6"
>       source = "github.com/hashicorp/amazon"
>     }
>   }
> }
> ```


Seems like this fixed it for me.  👍

**Comment by richardsonky** [comment]
Might be worth noting for those in my situation, you need to convert to hcl, along with the fix above. I was attempting to use json syntax.  After converting to hcl it works.  Guess it's time...

**Comment by gek0** [comment]
I've already migrated from JSON to HCL syntax since `init` is not needed/works for JSON configuration.
I've managed to get this working for me as well now. 

The thing that helped was to remove the cached plugin directory (**~/.packer.d/plugins/github.com/hashicorp/amazon**/) and re-run the init command.
After that validation and build stages work normally. Thanks @roman8422 for the fix!
