### ISSUE TITLE
Error: amazon-ebs: Error querying AMI: UnauthorizedOperation: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by krish2497** [hashicorp/packer-plugin-amazon#177]
Hi there,
I was trying to create Amazon linux 2 AMI when I encountered the error. I am using the limited EC2 access policy. Please guide what could be the missing permission in the attached policy(iam_policy_packer.log). I am an user in AWS account and my user has same IAM policy applied. 

Error:
`amazon-ebs: output will be in this color.

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: test_tableau_ami
==> amazon-ebs: Error querying AMI: UnauthorizedOperation: You are not authorized to perform this operation.
==> amazon-ebs: 	status code: 403, request id: 43edddc2-9bdd-4fab-836f-62fcde035979
Build 'amazon-ebs' errored after 1 second 901 milliseconds: Error querying AMI: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 43edddc2-9bdd-4fab-836f-62fcde035979

==> Wait completed after 1 second 901 milliseconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 43edddc2-9bdd-4fab-836f-62fcde035979

==> Builds finished but no artifacts were created.`

[iam_policy_packer.log](https://github.com/hashicorp/packer/files/7862055/iam_policy_packer.log)

**Comment by nywilken** [comment]
👋 If you're still struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.
