### ISSUE TITLE
packer-plugin-amazon_v1.0.7_x5.0_linux_amd64 fails while creating temporary keypair

### ISSUE THREAD

**Issue by Pablolio88** [hashicorp/packer-plugin-amazon#184]
While baking image using packer-plugin-amazon_v1.0.7_x5.0_linux_amd64 process fails on creating the temporary keypair
Builder: amazon-ebs

#### Reproduction Steps

Running "packer build" command while creating Windows AMI.

### Plugin and Packer version

Packer version: 1.7.3 [go1.16.5 linux amd64]

### Operating system and Environment details

Jenkins 2.319.1

### Log Fragments and crash.log files
packer-plugin-amazon_v1.0.7_x5.0_linux_amd64 plugin: 2022/01/26 08:56:39 Retryable error: InvalidParameterValue: 1 validation error detected: Value '' at 'keyType' failed to satisfy constraint: Member must satisfy enum value set: [rsa, ed25519]

**Comment by JenGoldstrich** [comment]
Hey @Pablolio88 thanks for reporting this,

I think this issue is likely due to changes made the temporary keypair in the newest release, can you post your build file?

**Comment by Pablolio88** [comment]
`source "amazon-ebs" "windows-6" {
  region = var.region

  ami_description = format("x - %s %s", var.component.name, coalesce(var.component.version, var.build.version))
  ami_regions     = var.ami_regions
  ami_name        = local.name
  source_ami_filter {
    filters     = length(keys(var.base_ami.filters)) > 0 ? var.base_ami.filters : local.filters.ami
    owners      = length(var.base_ami.owners) > 0 ? var.base_ami.owners : ["self", "xxxx"]
    most_recent = true
  }

  # EC2 settings
  disable_stop_instance                 = true
  instance_type                         = local.spot_type ? null : var.instance_type
  shutdown_behavior                     = var.instance_shutdown_behavior
  spot_instance_types                   = local.spot_type ? var.spot_instance_types : null
  spot_price                            = var.spot_price
  temporary_key_pair_name               = local.name
  temporary_security_group_source_cidrs = ["10.0.0.0/8"]
  subnet_filter {
    filters = local.filters.subnet
    random  = true
  }
  vpc_filter {
    filters = local.filters.vpc
  }
  user_data = <<-EOF
      xxx
  EOF


  # Communicator and its parameters
  communicator   = "winrm"
  winrm_insecure = true
  winrm_password = var.ansible_password
  winrm_username = local.platform.username
  winrm_use_ssl  = false

  skip_create_ami = var.skip_create_ami

  # Tagging
  run_tags        = merge(local.tags.default, local.tags.component)
  run_volume_tags = local.tags.default
  snapshot_tags   = merge(local.tags.default, local.tags.component)
  spot_tags       = local.spot_type ? local.tags.default : null
  fleet_tags      = local.spot_type ? local.tags.default : null
  tags            = merge(local.tags.default, local.tags.component)
}
`

**Comment by JenGoldstrich** [comment]
Hrm, that's strange I would expect this to work with no temporary_key_pair_type set, I'll investigate this, in the mean time if you specify your temporary_key_pair_type in your build file as "rsa" this should let you bypass this issue in the mean time

**Comment by Pablolio88** [comment]
build {
  sources = [
    "source.amazon-ebs.windows-6"
  ]

  provisioner "ansible" {
    ansible_env_vars = [
      "ANSIBLE_HOST_KEY_CHECKING=False",
      "ANSIBLE_PIPELINING=True",
      "ANSIBLE_NOCOLOR=False"
    ]
    command      = "ansible-playbook"
    empty_groups = []
    extra_arguments = compact(
      flatten([
        local.ansible_extra_args,
        [for k, v in var.ansible_extra_vars : ["--extra-vars", format("%s=%s", k, v)]],
        ["--extra-vars", "ansible_password=${var.ansible_password}"],
        ["--extra-vars", "ansible_user=${local.platform.username}"]
      ])
    )
    # galaxy_file = local.ansible_galaxy_file
    # galaxy_force_install = false
    groups              = concat(var.ansible_groups, [replace(var.component.name, "-", "_")])
    host_alias          = replace(var.component.name, "-", "_")
    inventory_directory = join("/", [var.ansible_workspace, "inventories", var.environment])
    skip_version_check  = false
    playbook_file       = local.ansible_playbook_file
    roles_path          = var.ansible_role_path
    use_proxy           = false
    user                = local.platform.username
  }

  # TODO: Remove the user account for provisioning
  provisioner "powershell" {
    environment_vars = []
    script           = script
  }

  post-processors {
    post-processor "manifest" {}
  }
}

**Comment by Pablolio88** [comment]
> Hrm, that's strange I would expect this to work with no temporary_key_pair_type set, I'll investigate this, in the mean time if you specify your temporary_key_pair_type in your build file as "rsa" this should let you bypass this issue in the mean time

Here us build section. I have provision steps using ansible

**Comment by JenGoldstrich** [comment]
I think if you pass in temporary_key_pair_type alongside temporary_key_pair_name as either RSA or ed25519 you should be in business for now.

**Comment by JenGoldstrich** [comment]
@nywilken looked into this and figured out that if you pass in a temporary_key_pair_name our code doesn't correctly default your temporary_key_pair_type, we are shipping a fix to this in https://github.com/hashicorp/packer-plugin-amazon/pull/185 and I will let you know @Pablolio88 when we have a release out that resolves this, thanks for reporting this so quickly after the release, appreciate it!

**Comment by JenGoldstrich** [comment]
Should be fixed in release v1.0.8, feel free to re-open if you're still having this issue on that version, thanks again for reporting!
