### ISSUE TITLE
HCL2 - vault_aws_engine

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-amazon#188]
_This issue was originally opened by @dtroup-global in https://github.com/hashicorp/packer/issues/11536 and has been migrated to this repository. The original issue description is below._

---
TLDR: allow using the `use_vault_aws_engine` in an aws datasource.

Hi, having an issue with the HCL2 formatted files. I’m converting a working json file to hcl, and using vault as part of the build. When converting the file it puts in an entry for the AWS authentication but it does not know how to handle the vault_aws_auth entry.

#### Reproduction Steps

packer validate base.json
packer build base.json

Both of these work

packer hcl2_upgrade base.json
fix a couple of issues with commands (change them to locals)
packer validate base.pkr.hcl

### Packer version

Packer v1.7.9

### Simplified Packer Template
```
data "amazon-ami" "ubuntu" {
  filters = {
    name                = "ubuntu-minimal/images/hvm-ssd/ubuntu-bionic-18.04-amd64-minimal-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["aws-marketplace"]
  region      = "eu-west-1"
  vault_aws_engine = {
    name = "myrole"
  }
}

packer {
  required_plugins {
    amazon = {
      version = "= 1.0.7"
      source  = "github.com/hashicorp/amazon"
    }
    inspec = {
      version = "= 1.0.0"
      source  = "github.com/hashicorp/inspec"
    }
    ansible = {
      version = "= 1.0.1"
      source  = "github.com/hashicorp/ansible"
    }
  }
}
```
### Operating system and Environment details

Tested on ubuntu 18.04 and Mac OS

### Log Fragments and crash.log files
```
Error: Unsupported argument

  on base.pkr.hcl line 44:
  (source code not available)

An argument named "vault_aws_engine" is not expected here. Did you mean to
define a block of type "vault_aws_engine"?
```
I also logged a discussion on the forum, here (https://discuss.hashicorp.com/t/hcl2-vault-aws-engine/34841) 
but so far no replies :(

**Comment by nywilken** [comment]
Hi there :wave:, I'm going to close this issue since there hasn't been any updates to it. But if you are still running into issues please feel free to leave a comment on the issue and we will gladly reopen.
