### ISSUE TITLE
amazon-import plugin throw error 400 saying InvalidParameterValue: The specified KMS key is not accessible

### ISSUE THREAD

**Issue by rajbir1982** [hashicorp/packer-plugin-amazon#225]
Packer version is latest.
packer create virtual machine on oracle vitualbox then exporting the ova file to s3 for image-import. s3 is encrypted and import-image is using KMS key for image encryption.
There were no changes in any code and was working till Wed 01 June 2:00 AM. after that it started giving this error. i suspect there might some change in aws import-image ami. 

```
2022/06/02 01:39:31 packer-post-processor-amazon-import plugin: Opening file builds/centos7_super/centos7_super-xyz.ova to upload
2022/06/02 01:39:31 ui: [0;32m    centos7_super (amazon-import): Uploading builds/centos7_super/centos7_super-xyz.ova to s3://<bucket>/centos7_super-xyz[0m
2022/06/02 01:40:03 ui: [0;32m    centos7_super (amazon-import): Completed upload of builds/centos7_super/centos7_super-xyz.ova to s3://<bucket>/centos7_super-xyz[0m
2022/06/02 01:40:03 packer-post-processor-amazon-import plugin: Calling EC2 to import from s3://<bucket/centos7_super-xyz
2022/06/02 01:40:04 packer-post-processor-amazon-import plugin: Retryable error: InvalidParameterValue: The specified KMS key is not accessible. If this is a default EBS CMK, please retry your request without specifying the key explicitly
2022/06/02 01:40:04 packer-post-processor-amazon-import plugin: 	status code: 400, request id: xyz-abc-lmn-ijk
```

**Comment by nywilken** [comment]
Hi @rajbir1982 thanks for reaching out. This may be an upstream issue that we need to look into. Can you please provide us with a redacted template configuration file that we can use to reproduce the issue. Along with the exact version of Packer and the Packer Amazon plugin being used. 

You can get the version for Packer by running `packer version` and the version of the plugin by running `packer plugins installed`.

**Comment by rajbir1982** [comment]
Hi, thanks for coming back. AWS confirmed it was a bug from their end.
import function with secret key was broken from their end. it is fixed and
my code is working fine now.

Regards,
Rajbir Singh

**Comment by nywilken** [comment]
Thanks for the follow up @rajbir1982 I'll close the issue and let the team now.
