### ISSUE TITLE
sha256 checksum file version 1.1.6

### ISSUE THREAD

**Issue by webminster** [hashicorp/packer-plugin-amazon#299]
Using Packer 1.7.10.  Was working before today 8 December 2022.  Today suddenly Packer will not initialize:

11:44:48  + packer --version
11:44:49  1.7.10
11:44:49  + grep -q init
11:44:49  + packer help
11:44:49  + packer init .
11:44:50  Failed getting the "github.com/hashicorp/amazon" plugin:
11:44:50  1 error occurred:
11:44:50  	* could not get sha256 checksum file for github.com/hashicorp/amazon version 1.1.6. Is the file present on the release and correctly named ? GET https://github.com/hashicorp/packer-plugin-amazon/releases/download/v1.1.6/packer-plugin-amazon_v1.1.6_SHA256SUMS: 404  []

My template.json.pkr.hcl contains:
packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.1"
      source = "github.com/hashicorp/amazon"
    }
  }
}

**Comment by bengaywins** [comment]
I just started experiencing this with a multi-stage pipeline too. Some builds finished, the next packer run within the same pipeline that depended on images built earlier in the pipeline, failed due to this same reasons.

**Comment by webminster** [comment]
Did commit "version: set 1.1.7 development version" 64c326478b8692fca872399693b0b7e5787b5ae0 break this?

**Comment by bengaywins** [comment]
Hah @webminster we just noticed there _is_ a new release now!

**Comment by bengaywins** [comment]
My builds are fixed now. ugh this caused a bunch of panic. lol
