### ISSUE TITLE
subnet_filter broken in 1.2.3

### ISSUE THREAD

**Issue by bryceml** [hashicorp/packer-plugin-amazon#367]
#### Overview of the Issue

subnet_filter doesn't work in 1.2.3

#### Reproduction Steps

Using 1.2.2 works, version 1.2.3 finds the wrong subnet

### Plugin and Packer version

From 1.2.3

### Simplified Packer Buildfile

```
  subnet_filter {
    filters = {
      "tag:purpose"     = "packer"
    }
    most_free = true
  }
```

### Operating system and Environment details

macos arm64

### Log Fragments and crash.log files

```
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin: 2023/04/19 15:02:55 Using Subnet Filters {
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:   Filters: [
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:     {
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:       Name: "tag:purpose",
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:       Values: ["packer"]
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:     }
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin:   ]
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin: }
    amazon-ebs.bastion: Found Subnet ID: subnet-[REDACTED]297144
2023/04/19 15:02:55 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin: 2023/04/19 15:02:55 [INFO] Finding AZ and VpcId for the given subnet 'subnet-[REDACTED]297144'
2023/04/19 15:02:56 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin: 2023/04/19 15:02:56 [INFO] AvailabilityZone found: 'us-east-1c'
2023/04/19 15:02:56 packer-plugin-amazon_v1.2.3_x5.0_darwin_arm64 plugin: 2023/04/19 15:02:56 [INFO] VpcId found: 'vpc-[REDACTED]650258'
==> amazon-ebs.bastion: Setting public IP address to true on instance without a subnet ID
==> amazon-ebs.bastion: Inferring subnet from the selected VPC "vpc-[REDACTED]650258"
==> amazon-ebs.bastion: Set subnet as "subnet-[REDACTED]517044c"
```

**Comment by aknosis** [comment]
I'm seeing something similar where packer is ignoring my configured vpc_id / subnet_id.

```
source "amazon-ebs" "ami" {
...
  vpc_id                      = var.build_vpc
  subnet_id                   = var.build_subnet
...
}
```

Log excerpt:

```
Setting public IP address to true on instance without a subnet ID
Inferring subnet from the selected VPC "vpc-XXX"
Set subnet as "subnet-XXX"
changing public IP address config to true for instance on subnet "subnet-XXXX"
Error launching source instance: InvalidParameterValue: Value (us-east-1c) for parameter availabilityZone is invalid. Subnet 'subnet-XXXX' is in the availability zone us-east-1e
```

**Comment by epierce78** [comment]
Same, our builds just started failing.  Similar logs.

**Comment by jcolfej** [comment]
We also have the same problem!
Our build use a pre-existing security group, the subnet selection doesn't check that the subnet is in the same AZ as the security group.
All our builds break...

**Comment by aknosis** [comment]
A quick resolution is to restrict the version:

```hcl
packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0, != 1.2.3"
      source  = "github.com/hashicorp/amazon"
    }
  }
}
```

**Comment by nywilken** [comment]
Hi Folks - thanks for bubbling this up. We will take a look at the released change to see what is going on. As a quick resolution you can pin the version of the AWS plugin to 1.2.2 or use the suggestion workaround by @aknosis 


```hcl
packer {
  required_plugins {
    amazon = {
      version = "= 1.2.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}
```

I suggest removing the v1.2.3 plugin as well. 

```shell
packer plugins remove github.com/hashicorp/amazon v1.2.3
```

If you are not using HCL templates but installed the latest release manually you can install v1.2.2 with the plugins install command. 

```shell
packer plugins install github.com/hashicorp/amazon v1.2.2
```

**Comment by lbajolet-hashicorp** [comment]
Hi,

Thanks for bringing that to our attention.

We fixed a problem with the `associate_public_ip_address` with v1.2.3 of the plugin (See https://github.com/hashicorp/packer-plugin-amazon/issues/18), but in doing so, we forgot to handle one case, leading to this problem, apologies for that.

We are releasing v1.2.4 as of now, which should become available within one hour. Normally this will fix this problem.

Please do let us know if you are still experiencing the problem.

Apologies again for the unexpected breakage.
