### ISSUE TITLE
release v1.2.5 has failed

### ISSUE THREAD

**Issue by adishM98** [hashicorp/packer-plugin-amazon#378]
the latest release v1.2.5 has failed. Could you please check the release action

**Comment by MatthewPugliese** [comment]
I second this ☝️

**Comment by MatthewPugliese** [comment]
Looks like a [context exceeded deadline](https://github.com/hashicorp/packer-plugin-amazon/actions/runs/4862838453/jobs/8669730242#step:7:62), so maybe just try re-triggering the job.

**Comment by webminster** [comment]
Retriggering didn't work for me:

 Failed getting the "github.com/hashicorp/amazon" plugin:
 1 error occurred:
 	* could not get sha256 checksum file for github.com/hashicorp/amazon version 1.2.5. Is the file present on the release and correctly named ? GET https://github.com/hashicorp/packer-plugin-amazon/releases/download/v1.2.5/packer-plugin-amazon_v1.2.5_SHA256SUMS: 404  []

This has stopped our builds again, after the 1.2.3 issue stopped them a week ago.  Can this be fixed ASAP or do we need to pin back to 1.2.4?
-Alan

**Comment by tayopal** [comment]
This has broken our Github Action pull request analysis-- ➕ to fixing this quickly.

**Comment by MatthewPugliese** [comment]
@tayopal @webminster @adishM98 looks like its fixed now.

**Comment by tayopal** [comment]
IMO this issue can be closed. TY

**Comment by lbajolet-hashicorp** [comment]
Hey,

Sorry about that, Github Actions had an outage when we first tried releasing the plugin earlier today.

This is fixed now, and the plugin v1.2.5 has been released now.
