### ISSUE TITLE
packer execution time has increased by two/four times after updating the version from 1.1.4 to any higher version

### ISSUE THREAD

**Issue by varunm17** [hashicorp/packer-plugin-amazon#449]
#### Overview of the Issue

We are customising many different OS as per our requirements. We were using the version `1.1.4` and we plan to use the latest version of the plugin (`1.2.9`), however after updating the plugin version we have observed that the build time has almost doubled in case of linux AMI's and for windows the build time has increased by almost 4 times.

#### Reproduction Steps

* Execute ansible playbook with version `1.1.4` and any higher version and you will observe the build times.
* We tested with all available version and we are summarising our observation about execution time

| **Operating System \ amazon packer plugin version**	 | **_1.1.4_**	| 1.1.5 |	1.1.6 |	1.2.0 |	1.2.1	 | **1.2.2**	| 1.2.3	| 1.2.4	| 1.2.5	| 1.2.6	| 1.2.7	| 1.2.8 | **1.2.9** |
|:---: | 	:---:  | :---:         |     :---:      |          :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |
|Amazon Linux 2|	**_14 minutes, 4 seconds_**	|35 minutes, 2 seconds	|34 minutes, 22 seconds	|35 minutes, 3 seconds	|36 minutes, 30 seconds	|33 minutes, 31 seconds|	36 minutes, 9 seconds	|34 minutes, 31 seconds|	34 minutes, 43 seconds	|34 minutes, 58 seconds	|37 minutes, 47 seconds	|35 minutes, 32 seconds|	35 minutes, 47 seconds|
|Ubuntu 20	|**_19 minutes, 16 seconds_**	|46 minutes, 12 seconds|	46 minutes, 58 seconds|	44 minutes, 25 seconds	|43 minutes, 43 seconds|	 43 minutes, 50 seconds	|44 minutes, 43 seconds	|44 minutes, 43 seconds	|44 minutes, 43 seconds	|50 minutes, 15 seconds	|46 minutes, 11 seconds	|43 minutes, 14 seconds	|43 minutes, 41 seconds|
|Ubuntu 22	|**_20 minutes, 44 seconds_**	|42 minutes, 44 seconds|	45 minutes, 5 seconds|	45 minutes, 39 seconds	|43 minutes, 1 seconds|	42 minutes, 43 seconds	|41 minutes, 40 seconds	|42 minutes, 52 seconds	|42 minutes, 34 seconds	|43 minutes, 14 seconds|	42 minutes, 26 seconds	|42 minutes, 56 seconds	|43 minutes, 26 seconds|
|Windows 2019	|**_22 minutes, 22 seconds_**	|1 hours, 22 minutes, 35 seconds	|1 hours, 22 minutes, 54 seconds	|1 hours, 24 minutes, 6 seconds|	1 hours, 42 minutes, 14 seconds|	1 hours, 25 minutes, 36 seconds	|1 hours, 18 minutes, 47 seconds	|1 hours, 22 minutes, 25 seconds	|1 hours, 21 minutes, 53 seconds	|1 hours, 40 minutes, 21 seconds	|1 hours, 19 minutes, 19 seconds|	1 hours, 23 minutes, 43 seconds	|1 hours, 26 minutes, 1 seconds|

### Plugin and Packer version

Packer version: `1.10.0 [go1.20.11 linux amd64]`
Ansibe packer plugin version : `1.1.1`

### Operating system and Environment details

Operating System:

- AmazonLinux2
- Ubuntu20
- Ubuntu22
- WindowsServer 2019

### Log Fragments and crash.log files

For sharing the logs we have executed only few ansible playbooks, hence the execution time is on the lower end  but still we can observe the execution time after upgrading the plugin has increased significantly

| Operating System \ amazon packer plugin version	 | 1.1.4 - log fragment gist URL| 1.1.4 - execution time	|  1.2.9 - log fragment | 1.2.9- execution time |
|:---: | :---:  | :---:| :---:  | :---:| 
|Amazon Linux 2| [amazon_linux_2_plugin_version_1.1.4.log](https://gist.github.com/varunm17/d54aaa5d8bfee1771799cafa0598fd0e) | 3 minutes, 17 seconds| [amazon_linux_2_plugin_version_1.2.9.log](https://gist.github.com/varunm17/12d829f19b963c6e74dd1658638cd4de) | 6 minutes, 55 seconds|
|Ubuntu 20| [ubuntu_20_plugin_version_1.1.4.log](https://gist.github.com/varunm17/a5789f67d7a62435668242309c2fa8a2) | 3 minutes, 6 seconds|[ubuntu_20_plugin_version_1.2.9.log](https://gist.github.com/varunm17/d90aa57dc953e1a0bd298423a1dc75e9) | 5 minutes, 51 seconds|
|Ubuntu 22| [ubuntu_22_plugin_version_1.1.4.log](https://gist.github.com/varunm17/f40a72862a69cd85b2e47eacdfc3b8ae) | 2 minutes, 26 seconds|[ubuntu_22_plugin_version_1.2.9.log](https://gist.github.com/varunm17/c40c63f7d7bb93deccd10d9ca1de090e) | 4 minutes, 38 seconds|
|Windows Server 2019| [windows_2019_plugin_version_1.1.4.log](https://gist.github.com/varunm17/0f79ff3e8f4f1b41b76288fb149766a6) | 3 minutes, 17 seconds and 3 minutes, 3 seconds |[windows_2019_plugin_version_1.2.9.log](https://gist.github.com/varunm17/bc5f980f8642fe4a78ee1774e0b993ba) | 9 minutes, 3 seconds and 14 minutes, 27 seconds |

**Comment by lbajolet-hashicorp** [comment]
Hi @varunm17,

Thanks for the report, with the current information however it'll be hard to figure out where the performance problem appears, so I'll request help from you to figure out the source of the problem if you can.

Could you share your configurations please? I've taken a quick look at the logs from one of your builds (AL2), looks like the script is slower for some reason (~4 minutes vs. 7 minutes), the plugin's version is the same, and the OS image looks similar as well from a quick look, so it could be a SSH-related problem potentially, but it's hard to say with just that information.

The script outputs something else in the 1.1.4 run however:

```
    main.amazon-ebs.xyz_ami: skipping: package-cleanup -q --leaves | xargs -l1 yum -y remove
    main.amazon-ebs.xyz_ami: due to package dep locale bug
```

Is there an error that causes this? I don't have access to the script that you're running, so it's hard to say, but if it exits prematurely, that might be why 1.14 is faster, no clue why that'd be though since the rest of the environment looks similar.

Is the host the same machine in both tests?

Also, may I ask your help in determining which version introduces the slowdown? Could you bisect all the versions from 1.1.4 -> 1.2.9, so we have a better idea where to look?

Thanks.

**Comment by varunm17** [comment]
hi @lbajolet-hashicorp,

Thanks you for your response. You can ignore the script output, from this issue we are specifically observing the slowness during execution of ansible playbooks. We do not see any errors just the execution time has increased as reported. You are correct we have everything in common in the environment except the packer amazon plugin versions.

The host is not the same machine. Each build spins up a fresh instance. But we are able to replicate this issue at our will.

The packer amazon plugin version where the execution time started to increase  is **`1.1.5`**.

Hope this helps.

**Comment by lbajolet-hashicorp** [comment]
Thanks for the follow-up.

Looking at the diff between 1.1.4 and 1.1.5, this should not change much as we only introduced a new option (`enable_unlimited_credits`) with this version (refer to PR #273 for context). We also started building with go 1.18 instead of 1.17, but this should not impact performance too.

By any chance, did you specify an instance type to run the builds on? Are you using spot instances? I'm wondering if the instance type picked changed between those two versions, which may explain why scripts are suddenly slower to execute on the instance.
Could you check that on your side and report to us? We'll see if that's something we can explain/fix/workaround.

**Comment by varunm17** [comment]
* the only change we did was to bump version `1.1.4` and `1.1.5` and the issue was reproduced
* after that we tried to test with all other version avaialble untill `1.2.9`, but none of the version was anywhere close to execution time of `1.1.4`
* hence we reverted back to using `1.1.4` and everything was back to normal.
* To gather ansible time execution we added the below `ansible.cfg`

```
[defaults]
bin_ansible_callbacks = True
callbacks_enabled = timer, profile_roles, profile_tasks
```

* Our packer config is like below(trimmed down version):

```
packer {
  required_plugins {
    amazon = {
      version = ">= 1.2.9"
      source = "github.com/hashicorp/amazon"
    }
    ansible = {
      version = ">= 1.1.1"
      source  = "github.com/hashicorp/ansible"
    }
  }
}
build {

  name = "main"

  sources = [
    "source.amazon-ebs.XYZ",
  ]

  provisioner "ansible-local" {
    clean_staging_directory = true
    staging_directory       = "/tmp/ansible"
    command                 = "GALAXY_DISPLAY_PROGRESS=1 ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ANSIBLE_CONFIG=/tmp/ansible/playbooks/ansible.cfg /usr/local/bin/ansible-playbook"
    extra_arguments = [
      # To debug ansible role, enable the below line
      # "-vvvv",
      var.ansible_playbook_tags,
      var.playbook_extra_vars,
      "--extra-vars \"ansible_python_interpreter=/bin/python3 NPTYPE=${var.os_nptype}\""
    ]
    playbook_dir   = "ansible"
    playbook_files = var.ansible_playbook
    galaxy_file    = "ansible/playbooks/requirements.yml"
  }

source "amazon-ebs" "XYZ" {
  ami_block_device_mappings {
    delete_on_termination = true
    device_name           = var.ami_block_device_name
  }
  ami_name             = "XYZAMI-${formatdate("YYYYMMDD-hhmm", timestamp())}-${var.release_id}-${var.product_os_and_version_and_variant}"
  iam_instance_profile = var.iam_instance_profile
  instance_type        = var.instance_type
  region               = var.region
  run_tags = {
    Name             = "Packer-${formatdate("YYYY-MM-DD-hh-mm-ss", timestamp())}-${var.release_id}-${var.product_os_and_version_and_variant}"
    SourceAMI        = data.amazon-ami.packer_source_ami.id   # Disable this line when we want to Hard Code AMI
    SourceAMIName    = data.amazon-ami.packer_source_ami.name # Disable this line wwhen we want to Hard Code AMI
   }
  run_volume_tags = {
    SourceAMI     = data.amazon-ami.packer_source_ami.id   # Disable this line when we want to Hard Code AMI
    SourceAMIName = data.amazon-ami.packer_source_ami.name # Disable this line when we want to Hard Code AMI
  }
  security_group_id        = var.security_group_id
  shutdown_behavior        = "terminate"
  source_ami               = data.amazon-ami.packer_source_ami.id # Disable this line when we want to Hard Code AMI
  ssh_file_transfer_method = "sftp"
  ssh_read_write_timeout   = "5m"
  ssh_username             = var.os_user
  temporary_key_pair_type  = "ed25519"
  subnet_id                = var.subnet_id
  tags = {
    Name             = "XYZAMI-${formatdate("YYYYMMDD-hhmm", timestamp())}-${var.release_id}-${var.product_os_and_version_and_variant}"
    OSDistribution   = var.os_code
    SourceAMI        = data.amazon-ami.packer_source_ami.id   # Disable this line when we want to Hard Code AMI
    SourceAMIName    = data.amazon-ami.packer_source_ami.name # Disable this line when we want to Hard Code AMI
    created          = local.timestamp
    decommissioned   = "0"
    distributed      = "0"
  }
  aws_polling {
    delay_seconds = 120
    max_attempts  = 60
  }

  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-new-instances.html#configure-IMDS-new-instances
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = var.hop_limit
  }
  # imds_support   = "v2.0"
  user_data_file = "packer/files/sshd_config.sh"
  vpc_id         = var.vpc_id
}

```

**Comment by varunm17** [comment]
thanks @lbajolet-hashicorp for your inputs, indeed we were using t3 instance, hence after Adding `enable_unlimited_credits = true` the execution time is back to normal, really appreciate your analysis and solution
