### ISSUE TITLE
[documentation] virtual_name for Block Device Mapping

### ISSUE THREAD

**Issue by hegyre** [hashicorp/packer-plugin-amazon#459]
Hello!

On the [current doc for EBS builder](https://developer.hashicorp.com/packer/integrations/hashicorp/amazon/latest/components/builder/ebs#launch_block_device_mappings), we can find this:

`virtual_name` (string) - The virtual device name. See the documentation on Block Device Mapping for more information.

There's no link at all as it's usually done for other parameters when referring to another part in the documentation.
Besides that, I was not able to find the relevant documentation. Did I missed something ?

**Comment by lbajolet-hashicorp** [comment]
Hi @hegyre,

The Block Device Mapping being referenced here is likely referring to the [AWS docs on device mapping](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html).

From what I gather, `virtual_name` is only for instance-based (ephemeral) volumes, any EBS-backed volume will have a snapshot-ID to back it.

The doc for the option isn't super clear though, I'll see to improve that soon, thanks for the pointer.

**Comment by hegyre** [comment]
Ah ok fine then I don't use ephemerals.
Yeah you can just update the docs with what you just wrote in your comment it's more clear.
