### ISSUE TITLE
Links in the docs are broken

### ISSUE THREAD

**Issue by amontalban** [hashicorp/packer-plugin-amazon#48]
#### Overview of the Issue

The links in the website (https://www.packer.io/docs/builders/amazon) are broken, for example:

[amazon-ebs](https://www.packer.io/docs/builders/amazon/ebs.mdx)

Looks like the problem is that most of the links have an `.mdx` extension and that is not correct, if you remove the extension the right page is shown.

**Comment by sylviamoss** [comment]
https://www.packer.io/docs/builders/amazon links are valid now! Thanks again.
