### ISSUE TITLE
Enable Fast Launch by Region

### ISSUE THREAD

**Issue by JasonLibeyTR** [hashicorp/packer-plugin-amazon#506]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The current way Fast Launch is supported assumes you want to enable it on all the regions you are copying the AMI to. The enable_fast_launch configuration is only at the root level of the Fast Launch configuration. There should be a way to disable Fast Launch for some regions.

#### Use Case(s)

An AMI that is baked is copied to multiple regions. Only one region sees heavy use and will benefit from having Fast Launch enabled. The other regions should not have to be enabled as that is a waste of resources/money.

#### Potential configuration

Add the enable_fast_launch boolean to the region_launch_templates array.
```
      "fast_launch": {
        "enable_fast_launch": "true",
        "region_launch_templates": [
          {"region": "us-east-1", "template_id": "lt-04eb90cb108a19b0b", "template_version": 6 },
          {"region": "us-west-2", "enable_fast_launch": "false" }
        ],
        "max_parallel_launches": 6,
        "target_resource_count": 5
      }
```

**Comment by lbajolet-hashicorp** [comment]
Hi @JasonLibeyTR,

Thanks for reporting this! I've just opened a PR that introduces `enable_fast_launch` to the `region_launch_templates` array, this will be rolled into an upcoming release of the plugin, but in the meantime (ideally before we merge it), may I ask you if you can test the plugin with this addition?

You'll need to compile and install it to your local environment, feel free to refer to our [docs](https://developer.hashicorp.com/packer/docs/plugins/install#manually-install-plugins-using-the-cli) for information on that, alternatively if you have `make` installed, you can invoke `make dev` which will build and install the plugin so you can run tests with it.
