### ISSUE TITLE
Please release v1.3.3

### ISSUE THREAD

**Issue by jaysoffian** [hashicorp/packer-plugin-amazon#510]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Please release v1.3.3. There's been a bunch of PRs [merged since v1.3.2](https://github.com/hashicorp/packer-plugin-amazon/compare/v1.3.2...main) which was released on April 17. The release before that was March 5. So v1.3.3 seems overdue.

#### Use Case(s)

In particular, I need arm64_mac arch support added with #487.

**Comment by lbajolet-hashicorp** [comment]
Hey @jaysoffian,

Thanks for the reminder; we are indeed due for a release, I'll try to schedule one for this week.

Sorry for not doing this earlier, I'll keep you posted!

**Comment by lorengordon** [comment]
@lbajolet-hashicorp Did the release actually complete successfully? I'm not seeing it here, https://github.com/hashicorp/packer-plugin-amazon/releases...

**Comment by lbajolet-hashicorp** [comment]
Hi @lorengordon,

It is in progress now! The issue got closed with the merge of the PR, but the release needs to have one more step - pushing the tag and starting the process.
This should be complete within the hour, you should be able to upgrade then!

**Comment by lorengordon** [comment]
Oh I see, thanks! Yeah, I assumed the merge would have triggered a pipeline to complete the release. Appreciate the ultra fast response, and the clarifcation!
