### ISSUE TITLE
Option to Fetch Secrets and Data from Parameter Store Instead of Secret Manager

### ISSUE THREAD

**Issue by 116davinder** [hashicorp/packer-plugin-amazon#95]
I see that packer have data source https://github.com/hashicorp/packer-plugin-amazon/tree/main/datasource/secretsmanager
which allows user to fetch secrets from Secret Manager, can we have a similar data source or parameter store?

Currently, I am using parameter store for almost all things.

**Comment by voanhduy1512** [comment]
probably fixes by #93

**Comment by sylviamoss** [comment]
Closing this one as now there's a parameterstore datasource! ☝🏼
